spring:
  rabbitmq:
    host: 192.168.220.128
    port: 5672
    username: guest
    password: guest

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000

hc:
  auth:
    accessTokenValiditySeconds: 186400
    refreshTokenValiditySeconds: 604800
    clients:
    - client: hc
      secret: 123456
      grantType: password,authorization_code,refresh_token
      scope: all