spring:
  rabbitmq:
    host: 192.168.220.128
    port: 5672
    username: guest
    password: guest
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceAutoConfiguration